### ISSUE TITLE
Fullscreen overlay sometimes fails to initialize with multiple clients

### ISSUE THREAD

**Issue by evevision** [evevision/evevision#2]
Starting EveVision **after** starting multiple clients of EVE can sometimes result in the fullscreen overlay (minimized windows menu) not initializing. It is random - sometimes all work, sometimes only a couple.

Starting the EVE clients one by one, however, does not cause this issue.

**Comment by evevision** [comment]
It seems Windows Defender may be contributing to this - after testing with unsafeInject and windows defender off, there is no issue and everything happens immediately.

With windows defender ON, the CPU usage of defender spikes and the windows take a while to initialize. It may be Defender interfering with the IPC.

**Comment by randornclawyer** [comment]
I can confirm that. With deactivated defender everything runs superfast & smooth.

**Comment by samoneilll** [comment]
Maybe it needs a new issue thread, but I cannot get the overlay to initialize at all. The first time I started EveVision then launched 2 clients, no overlay. Tried some combinations of EveVision then single client, launch client first then EveVision, tried with windows real-time protection on and off (defender appears to be only a firewall now and not anti-malware?), but no overlay. 

Edit: mkocus's comment jogged my memory. I also tried closing eve-o preview and fraps that were also creating overlays.

Final-edit: Resolved by completely exiting FRAPS, this was the cause of the overlay not initializing correctly

**Comment by mkocus** [comment]
Same here. Until know I've managed to make it work 2 times. I've even compiled it from the source, but no obvious error code is thrown on console via yarn dev launch.

Maybe some other overlay is breaking it? It simply does not shows in 95% cases.

(edit) Oh, and I use single client, in Fixed Window setting.

**Comment by evevision** [comment]
@mkocus Are you running DX9 or 11? Only 11 is supported. This wasn't made obvious until today.

**Comment by mkocus** [comment]
DX11. Yeah, I saw that readme edit earlier.

**Comment by mkocus** [comment]
Looking at the output of yarn dev, it seems that everything has been initialized properly, it finds window, character ID, inject with success - but overlay cannot be seen.

**Comment by evevision** [comment]
Is your Windows Defender enabled? We've been getting reports of WD interfering with the initialization process right at the exact step you're mentioning. I need to take a closer look at all the IPC stuff this week.

**Comment by evevision** [comment]
> Looking at the output of yarn dev, it seems that everything has been initialized properly, it finds window, character ID, inject with success - but overlay cannot be seen.
> 
> (EDIT) found something interesting: It seems that overlay is being added, is recognized (because cursor changes to different one, and the EVE window is not responsive in the sector where overlay should be), but it is NOT visible :D

Is your Windows Defender enabled? We've been getting reports of WD interfering with the initialization process right at the exact step you're mentioning. I need to take a closer look at all the IPC stuff this week.

**Comment by mkocus** [comment]
I do not use WD, i use Eset smart security - but I've tried whitelisting / disabling all functions and nothing worked.

**Comment by evevision** [comment]
closing, we'll track in the more generic issue #6
