### ISSUE TITLE
ChildWindow initializes with incorrect size until parent window is resized

### ISSUE THREAD

**Issue by ghost** [evevision/evevision#22]
Occasionally, when attempting to launch a window from the Tools menu, the page doesn't fully render.  Issue resolves when you resize the window.  Here is a short clip of the bug in action: https://streamable.com/n2hjd0

Doesn't seem to be limited to a specific site or window size.  I've resized the windows and can consistently get the issue to re-appear ~20% of the time.

Doesn't seem to be associated with UI scaling or resolution.  I was able to reproduce the issue at 1920x1080 and 2560x1440, using both Windowed Mode, Fixed Window, and Fullscreen.

**Comment by evevision** [comment]
Thank you for the report. It appears the ChildWindow isn't receiving the correct size initially.

What version did you experience this issue in?

**Comment by ghost** [comment]
From the latest - 0.4.2

**Comment by evevision** [comment]
Was the issue present in 0.4.1 at all?

**Comment by ghost** [comment]
No - I've re-downloaded 0.4.1 and am unable to reproduce it there.

**Comment by evevision** [comment]
Okay, will need to compare commits between 0.4.1 and 0.4.2 then. I don't recall messing with ChildWindow rendering, but I could be wrong. Thank you!

If anyone else runs into this in the meantime, please let me know if it was present in 0.4.1 for you.

**Comment by evevision** [comment]
I can confirm myself that this occurs in 0.4.2. Will review soon.

**Comment by evevision** [comment]
Fixed by adding delay in 76f2c64c056efcede5c38b312c88a6b401c455b9
