### ISSUE TITLE
Doesn't work in Windowed borderless

### ISSUE THREAD

**Issue by smatthews0** [evevision/evevision#3]
Evevision doesn't work for windows borderless. (Doesn't load up) you get the prompt to say it's running but doesn't show up.

You can get around it by running the client in Fixed windows, Loading Evevision wait for it to load up and then switch back to Windows borderless

**Comment by evevision** [comment]
I'm almost certain this is due to the injector module not finding a 'top window' with the `EVE - CharacterName`. Need to change how I find the game.

**Comment by smatthews0** [comment]
Closing as Windows mode just takes longer to inject
