### ISSUE TITLE
request: user-added tools/shortcuts

### ISSUE THREAD

**Issue by echod** [evevision/evevision#36]
It would be great if there were a section for users to add their own custom URLs to open in the browser. Maybe even make the whole thing modular where users can add and remove headings and manage the shortcuts within them. Either way, personalization options would be amazing.

**Comment by evevision** [comment]
This is planned. The whole tools UI needs to be overhauled - it's just a crappy list of buttons. If you have any particular ideas, comments are welcome in issue #15
