### ISSUE TITLE
Tripwire fails to load graph, google CSS incorrect, some external apps refuse to load

### ISSUE THREAD

**Issue by november781** [evevision/evevision#5]
1. Tripwire fails to load graphs
2. Google's CSS looks kinda funky
3. Some web-apps refuse to be loaded (EvE-Scout's co-pilot is the first one I tried that failed to load)

Minor nit-pick: I would like to be able to make my own bookmarks in the tools window for quickly navigating back to a webpage. Also a URL bar would be amazing

**Comment by evevision** [comment]
2 is related to #17 , I didn't realize Google sends different CSS based on what your user agent is. Will fix.

I'll look into the other issues.

There will be a generic webbrowser with an address bar and all the usuals soon.

**Comment by evevision** [comment]
Issue 2 should be resolved now with #17, will leave issue open for the other two

**Comment by evevision** [comment]
Closing issue as most of this is resolved/being resolved in another issue.
