### ISSUE TITLE
Overlay initialization is unreliable or not working at all for a small percentage of users

### ISSUE THREAD

**Issue by evevision** [evevision/evevision#6]
We haven't entirely tracked down the cause(s), but the initialization process of EveVision appears to be interfered with on some machines for various reasons and with various symptoms - but all ultimately resulting in "I don't see anything". Some appear to be a title finding issue due to only injecting after changing window modes, others appear to be an issue with Windows Defender (or something) slowing down or flat out stopping IPC. In some scenarios, it has issues injecting multiple clients but always succeeds with some of them - this was proven to be caused by Windows Defender on one machine.

The unfortunate part is that I didn't log this area very well, and much less to a file, so it's been very hard to debug. I'm now working on cleaning up and documenting the entire process and ensuring that the whole process is logged so I can immediately see where the disconnect is happening in the future.

Until this issue is confidently resolved, any 'my overlay isn't showing up' issue reports should go here, as they are all likely linked, despite being different symptoms.

**Comment by evevision** [comment]
#19 related

**Comment by evevision** [comment]
Switching to unsafeInject worked for one user. I have a feeling it might work for everyone. Going to release 0.4.2 with unsafeInject.

**Comment by mkocus** [comment]
Do you need any debuging / logs help with that?

**Comment by evevision** [comment]
> Do you need any debuging / logs help with that?

@mkocus Just the person I was looking for! Are you on Discord? I'd like to test this build with you too.

**Comment by mkocus** [comment]
> > Do you need any debuging / logs help with that?
> 
> @mkocus Just the person I was looking for! Are you on Discord? I'd like to test this build with you too.

I'm now, as @Kocus there.

**Comment by evevision** [comment]
I'm closing this, as it seems that the issue no longer lies with EveVision itself, rather it is various conflicts with various third party software. The main culprit is right now appears to be RivaTuner Statistics Server, which is a fairly common piece of software that is also bundled with another common piece of software known as MSI Afterburner.

There was an issue for a couple of people due to the DLL injection mechanism used, but that was fixed in 7bcada9. Every log I've seen so far has otherwise had no issue initializing, only actually drawing to the screen.

At this point the only issue @mkocus is having (after disabling RivaTuner) is with retrieving character IDs after a relog which I will be opening another issue for.
